### ISSUE TITLE
SHA256 mismatch attempting to install on macOS

### ISSUE THREAD

**Issue by mjstrasser** [JosueMolinaMorales/mutant-kraken#31]
**Describe the bug**
I attempted to install Mutant Kraken on my Mac but Homebrew failed with **SHA256 mismatch** error.

**To Reproduce**
On my Mac:
1. I ran `brew tap JosueMolinaMorales/mutant-kraken` and it was successful
2. I ran `brew install mutant-kraken` and it showed:

```
==> Fetching josuemolinamorales/mutant-kraken/mutant-kraken
==> Downloading https://github.com/JosueMolinaMorales/mutant-kraken/releases/download/v0.1.4/mutant-kraken-macos.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/603864986/0a5b2dd5-71e4-498f-9138-d00e6b8392f1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential
########################################################################################################################################################################################### 100.0%
Error: mutant-kraken: SHA256 mismatch
Expected: bc4387e1d56055633e9646176e5727451c400cb5bbc6d3dd3d61162774ef3d16
  Actual: 94fd56112bbb76398e489d17b90cba90ff0d67bda5a85a7a6c6e9c8590f15347
    File: /Users/michael/Library/Caches/Homebrew/downloads/38a310703c8b67dab4ea1083726423054fc13067868229a7031beaa6ed2d55c0--mutant-kraken-macos.tar.gz
To retry an incomplete download, remove the file above.
```

**Expected behavior**
I expected the tool to install successfully.

**Desktop:**
 - OS: macOS
 - Version: Sonoma 14.5

**Comment by JosueMolinaMorales** [comment]
Thanks for the catch! Must be an issue with how the sha is saved during ci. Will look into it.

**Comment by JosueMolinaMorales** [comment]
Ok after looking into it, it seems like when tag 0.1.4 was released to github, the sha ending in `5347` was the one that was associated with this release but there releases after this that were made that did not update the tag but updated the homebrew config which changed the sha. looking into a fix so this doesnt happen again.

**Comment by mjstrasser** [comment]
Thanks @JosueMolinaMorales for fixing that.

I still had problems until I ran `brew untap JosueMolinaMorales/mutant-kraken` and then `brew tap JosueMolinaMorales/mutant-kraken` again.
